import Head from 'next/head';

export default function Page() {
  return (
    <>
      <Head>
        <title>Hello, world!</title>
        <meta name="description" content="Generated by create next app." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        <h1 className="text-9xl font-light underline">Hello, world!</h1>
        <p className="mx-2 my-8">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas repellat totam nostrum, vero fugit adipisci quo
          distinctio repudiandae suscipit. Odit quod impedit doloremque iure voluptates dolorum excepturi molestiae
          ipsam placeat. Asperiores provident amet dicta quam ratione architecto alias! Commodi neque odio veniam fuga
          aspernatur ut rerum, error quisquam sed cupiditate suscipit, architecto doloribus, dolore quam ex officiis. A,
          molestiae beatae? Fugiat aliquid sed, dolorem cupiditate fuga corrupti repellat rerum magnam sapiente, amet
          cum, rem nam debitis. Ea veritatis quis vel inventore, aliquam quos. Expedita voluptatem quidem repellendus
          nobis libero nihil? Magnam laudantium eos natus quibusdam ipsa earum doloremque itaque quis odio, explicabo
          cum, fuga rem dolor. At alias dolorum maxime cumque nesciunt, quibusdam sed sequi rerum molestias repudiandae,
          velit facilis! Minus vero laboriosam, consectetur rerum hic est necessitatibus iure, debitis unde adipisci,
          sunt quibusdam harum repudiandae explicabo aut dicta! Autem quis perferendis ipsam distinctio. Sed consectetur
          esse assumenda velit nesciunt! Dolore delectus adipisci iste explicabo reprehenderit, laudantium iure
          praesentium esse optio at molestiae fugit unde tempore, distinctio quos accusantium mollitia! Numquam quaerat
          rerum fuga et provident, reiciendis laborum aspernatur dolorum! Quis laborum beatae deleniti dolore modi autem
          saepe. Autem ad labore similique non sed hic quisquam. Repellat, impedit illo. Vel ullam possimus asperiores
          nemo sequi suscipit, aut eos magnam praesentium? Obcaecati consequatur rerum nobis delectus! Amet laborum quia
          facere quidem eius numquam nihil laudantium vel aspernatur, harum aperiam eveniet vero accusantium cumque unde
          consectetur sit, pariatur ipsa repudiandae eos animi? Nostrum unde necessitatibus iste voluptas maiores modi
          reiciendis non, assumenda nobis quos, possimus debitis illo accusamus ipsum doloribus repellat blanditiis quam
          nam eum aperiam quisquam veritatis. Quae, blanditiis aspernatur. Odit! Hic cumque alias est architecto dolore
          officiis amet quaerat delectus, aut excepturi! A, dolore autem quaerat sit architecto placeat quisquam totam,
          minima dicta, quibusdam provident. Recusandae dignissimos placeat tempora facere!
        </p>
      </main>
    </>
  );
}
